FROM alpine:latest
MAINTAINER Philipp Schmitt <philipp@schmitt.co>

ENV ARCH=x86_64

RUN apk --no-cache --virtual deps add git && \
    git clone https://github.com/50ButtonsEach/fliclib-linux-hci /tmp/src && \
    cp /tmp/src/bin/${ARCH}/flicd /usr/bin/flicd && \
    chmod +x /usr/bin/flicd && \
    mkdir /config && \
    rm -rf /tmp/src && \
    apk del deps

WORKDIR /config
VOLUME ["/config"]
EXPOSE 5551
ENTRYPOINT ["/usr/bin/flicd", "-f", "/config/db", "-s", "0.0.0.0", "-p", "5551"]
